### ISSUE TITLE
value_from_file causes an exception if the file does not exist

### ISSUE THREAD

**Issue by joejulian** [atbell/salt-consul#33]
The following error occurs if a state uses the value_from_file option and the file does not exist.

[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1542, in call
    self.verify_ret(ret)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 781, in verify_ret
    ).format(','.join(bad)))
SaltException: The following keys were not present in the state return: name,changes

**Comment by systembell** [comment]
Thx for catching this @joejulian.

**Comment by joejulian** [comment]
Closing this to get it off my issues tab. After this long it's probably not even valid anymore.
